Feature/better rename control bus 91
Weichwarenprojekt/Assembus pull request #24
Opened 2020-12-15 18:25 UTC by Dankrik42

Pull request for better rename control, apply renaming by click outside the item or press enter, leave renaming by press escape. Scroll to added group/assembly station and start renaming

2020-12-15 19:11 UTC, luismoser99 approved these changes
Good!

2020-12-22 11:30 UTC, failipp commented
While the mouse is over an item that currently is being renamed, scrolling the list view doesn't work.

2020-12-22 11:34 UTC, failipp commented
During the smooth scrolling, normal scrolling doesn't work. This is annoying if I don't want to rename the newly created group. And at the end when the scrolling is so slow, it seems to be over but it isn't and it resets the scroll position.

2020-12-22 12:28 UTC, failipp requested changes

2020-12-22 12:28 UTC, pscheede commented on Assembus/Assets/Scripts/MainScreen/Sidebar/HierarchyView/HierarchyItemController.cs
> -            // Save the item state
Why did this comment get removed?

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/MainScreen/Sidebar/HierarchyView/HierarchyViewController.cs
> +        public ScrollRect scroll;
These two variables could be named better, more descriptive.

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/MainScreen/Sidebar/HierarchyView/HierarchyViewController.cs
> +            var lowerBorder = topBorder + 1000;
Can this constant also be calculated dynamically? With the upcoming searchbar and possible other UI changes, someone might forget to change this value.

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/MainScreen/Sidebar/HierarchyView/HierarchyViewController.cs
> +                               scrollRect.transform.InverseTransformPoint(targetItem.position).y;
Why did you use `scrollRect.InverseTransformPoint` once and `scrollRect.transform.InverseTransformPoint` the other time?

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/Shared/InterpolatedFloat.cs
> +    public class InterpolatedFloat
Please remove compiler warnings. Take a look at this line in rider.

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/MainScreen/Sidebar/HierarchyView/HierarchyViewController.cs
> +            while (interpolatedFloat != targetValue)
Have you tried to fix the warning in this line? I know it technically is wrong but maybe it can be fixed?

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/Shared/InterpolatedFloat.cs
> +        /// <returns></returns>
Descriptions in docstring missing

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/Shared/InterpolatedFloat.cs
> +        /// <returns></returns>
Descriptions in docstring missing

2020-12-22 12:28 UTC, failipp commented on Assembus/Assets/Scripts/Shared/InterpolatedFloat.cs
> +        public float Value()
If you have a getter you should use a property with a private setter.

`public float Value { get; private set; }`

2020-12-22 21:38 UTC, failipp commented
We should also consider using automatic scrolling when something is added with a redo.

2020-12-22 21:48 UTC, failipp commented
When creating a new group, renaming is started. After this renaming, a RenameCommand is added to the undo history. This might not be intuitive, because if I rename a group directly after creating it, I don't expect that an undo will change the name back to "Group". Same for assembly stations.

In the same step you could also add a check if the new name is the same as the old name and don't do anything if so. This was forgotten in a previous feature and could be easily changed here.

2021-01-05 13:04 UTC, failipp approved these changes

2021-01-05 13:54 UTC, merged