feature/altering-component-groups-bus-14
Weichwarenprojekt/Assembus pull request #7
Opened 2020-11-17 20:39 UTC by Timbogen

2020-11-17 21:03 UTC, stefan-rink submitted a review, later dismissed

2020-11-17 21:03 UTC, stefan-rink commented on Assembus/Assets/Scripts/MainScreen/CameraController.cs
> +        public void UpdateCameraFocus(GameObject go)
Missing Doc Comment

2020-11-17 21:44 UTC, luismoser99 commented on Assembus/Assets/Scripts/MainScreen/CameraController.cs
> +        public void UpdateCameraFocus(GameObject go)
Fixed :)

2020-11-17 22:08 UTC, Dankrik42 commented on Assembus/Assets/Scripts/MainScreen/Sidebar/HierarchyView/HierarchyItemController.cs
> +        public DoubleClickDetector clickDetector;
Mayby naming the DoubleClickDetector doubleClickDetector because there alway can be a "SingleClickDetector"

2020-11-17 22:27 UTC, Dankrik42 commented on Assembus/Assets/Scripts/MainScreen/CameraController.cs
> +        public DoubleClickDetector clickDetector;
less specific name, because there can also be a singleclickdetector

2020-11-17 22:37 UTC, failipp requested changes

2020-11-17 22:37 UTC, failipp commented on Assembus/Assets/Scripts/MainScreen/Sidebar/HierarchyView/HierarchyItemController.cs
> +        private void UpdateButton()
This method does not have a good name, "Button" is too general.

2020-11-17 22:37 UTC, failipp commented on Assembus/Assets/Scripts/MainScreen/CameraController.cs
> +        public DoubleClickDetector clickDetector;
Naming is not exact, use doubleclickdetector

2020-11-17 22:39 UTC, luismoser99 approved these changes
OK!

2020-11-17 22:57 UTC, Dankrik42 approved these changes

2020-11-18 00:06 UTC, failipp approved these changes

2020-11-18 00:14 UTC, merged